### ISSUE TITLE
Add resolver support for CIDv1 and Base32

### ISSUE THREAD

**Issue by lidel** [ipfs/js-ipfs-http-response#8]
_(part of Migration to CIDv1 https://github.com/ipfs/ipfs/issues/337)_

### Problem

Right now only `multihash` resolver exists and it  means directory listing assumes everything is CIDv0 in Base58btc:

https://github.com/ipfs/js-ipfs-http-response/blob/4f1ace2917e344eb8e0148034923b75e3820122d/src/resolver.js#L54

https://github.com/ipfs/js-ipfs-http-response/blob/4f1ace2917e344eb8e0148034923b75e3820122d/src/resolver.js#L75

This means response for https://js.ipfs.io/ipfs/bafybeibrpdf53xmnhkspaiyo46hqw6avk3vo3tvggwc2szzybd2a5cn24y/img/  is an error:

> ![error screenshot_21](https://user-images.githubusercontent.com/157609/43845884-540799bc-9b2d-11e8-8259-9f11fe6923b7.png)

(when js-ipfs is running in service worker)

### Solution

`resolver.multihash` should be removed/deprecated and replaced by base-agnostic `resolver.cid`

**Comment by vasco-santos** [comment]
Hello @lidel , thanks for reporting this! 👍 

Create a PR with the proposed solution please 🙂
